### ISSUE TITLE
Update log-in & signup logic on backend

### ISSUE THREAD

**Issue by ghost** [rhandley1231/FinancialApp#2]
We need to update our data model to use the fields we came up with during our meetings: 
- Integrate the necessary logic to update the FreeSQL database on signup (Check that all necessary fields have been entered as needed)
- Integrate the necessary logic to perform a login validation (check if a username exists in the database and match the password)
- Don't worry about 2FA right now, but still collect phone numbers and emails for when we do make this change
- Tomcat is the default servlet of spring boot.
- See the model, view, and controller folders in the backend for starter code and work on improving what's there.

**Comment by KMalone42** [comment]
Going to try and do this tonight.
